[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Static asset optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API routes - no cache
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Environment variables are set in Netlify dashboard
# Go to Site settings → Environment variables to configure:
# 
# Required variables:
# JWT_SECRET
# NEXTAUTH_SECRET
# NEXTAUTH_URL
# NEXT_PUBLIC_APP_NAME
# NEXT_PUBLIC_APP_URL
# LOG_LEVEL
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# USE_SUPABASE (set to 'true')
# 
# For push notifications:
# NEXT_PUBLIC_VAPID_PUBLIC_KEY
# VAPID_PRIVATE_KEY
# VAPID_EMAIL
# 
# For image uploads:
# CLOUDINARY_URL

# The @netlify/plugin-nextjs plugin automatically handles:
# - API routes (/api/*)
# - Static file serving
# - Client-side routing
# - Server-side rendering