[build]
  command = "npm ci && npm i && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables are set in Netlify dashboard
# Go to Site settings → Environment variables to configure:
# 
# Required variables:
# MONGODB_URI
# MONGODB_DB_NAME  
# JWT_SECRET
# NEXTAUTH_SECRET
# NEXTAUTH_URL
# NEXT_PUBLIC_APP_NAME
# NEXT_PUBLIC_APP_URL
# MDB_MCP_API_CLIENT_ID
# MDB_MCP_API_CLIENT_SECRET
# LOG_LEVEL
# NODE_ENV

# The @netlify/plugin-nextjs plugin automatically handles:
# - API routes (/api/*)
# - Static file serving
# - Client-side routing
# - Server-side rendering