[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Environment variables are set in Netlify dashboard
# Go to Site settings → Environment variables to configure:
# 
# Required variables:
# Key: NEXT_PUBLIC_SUPABASE_URL
# Value: [Your Supabase project URL]
# 
# Key: NEXT_PUBLIC_SUPABASE_ANON_KEY 
# Value: [Your Supabase anonymous key]
# 
# Key: SUPABASE_SERVICE_KEY
# Value: [Your Supabase service role key]

# Variable 4:
# Key: JWT_SECRET
# Value: 941efef2eb57df7ebdcaae4b62481d14cd53d97e6fc99641e4a3335668732766

# The @netlify/plugin-nextjs plugin automatically handles:
# - API routes (/api/*)
# - Static file serving
# - Client-side routing
# - Server-side rendering

# No manual redirects needed - the plugin handles everything 