[build]
  command = "npm run build:fresh-bash"
  publish = ".next"

# Clear all caches for fresh deployment
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"
  # Force fresh npm install and clear caches
  NPM_CONFIG_CACHE = ""
  NPM_CONFIG_PREFER_OFFLINE = "false"
  # Clear Netlify-specific caches
  NETLIFY_CACHE_NEXTJS = "false"
  # Force fresh git checkout
  NETLIFY_BUILD_COMMAND_FRESH = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Clear build cache on every deploy
[[headers]]
  for = "/*"
  [headers.values]
    X-Fresh-Deploy = "true"

# Environment variables are set in Netlify dashboard
# Go to Site settings → Environment variables to configure:
# 
# Required variables:
# Key: NEXT_PUBLIC_SUPABASE_URL
# Value: [Your Supabase project URL]
# 
# Key: NEXT_PUBLIC_SUPABASE_ANON_KEY 
# Value: [Your Supabase anonymous key]
# 
# Key: SUPABASE_SERVICE_KEY
# Value: [Your Supabase service role key]

# The @netlify/plugin-nextjs plugin automatically handles:
# - API routes (/api/*)
# - Static file serving
# - Client-side routing
# - Server-side rendering