[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL = "https://gpgenilthxcpiwcpipns.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
# JWT_SECRET = "your-jwt-secret"

# API Routes configuration
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__nextjs"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Default fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 